# Generated by Django 6.0 on 2026-01-01 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('species', models.CharField(choices=[('CANINE', 'Canine'), ('FELINE', 'Feline'), ('AVIAN', 'Avian'), ('RODENT', 'Rodent'), ('REPTILE', 'Reptile'), ('AMPHIBIAN', 'Amphibian'), ('FISH', 'Fish'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('microchip', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tutors.tutor')),
            ],
        ),
    ]
