# Generated by Django 6.0.1 on 2026-01-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutors.tutor'),
        ),
    ]
