# Generated by Django 6.0.1 on 2026-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_time_constraint'),
        ('doctors', '0002_doctor_created_at_doctor_updated_at'),
        ('patients', '0002_alter_patient_tutor'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'scheduled'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled'), ('NO_SHOW', 'no_show')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'starts_at'], name='appointment_doctor__60bd67_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'starts_at'], name='appointment_patient_c89bba_idx'),
        ),
    ]
